//? FunciÃ³n anonÃ­ma auto invocada
(() => {

    const displayError = ( message: string ): never => {

        throw new Error(message);

    }

    displayError('Auxilio ðŸ¥¹');

})();